# Generated by Django 5.0 on 2023-12-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pickup', models.CharField(choices=[(1, 'Oshodi'), (2, 'Cele Exp.'), (3, 'Ajah'), (4, 'Lekki'), (5, 'Festac'), (6, 'Ojota')], default='Oshodi', max_length=10)),
                ('destination', models.CharField(choices=[(1, 'Oshodi'), (2, 'Cele Exp.'), (3, 'Ajah'), (4, 'Lekki'), (5, 'Festac'), (6, 'Ojota')], max_length=10)),
                ('trip', models.CharField(choices=[(1, 'One way'), (2, 'Two way')], default='Two way', max_length=20)),
                ('start_time', models.TimeField()),
            ],
        ),
    ]
