# Generated by Django 5.0 on 2023-12-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='start_time',
            field=models.CharField(choices=[(1, '07:00'), (2, '08:00'), (3, '12:00'), (4, '13:00'), (5, '17:00')], max_length=15),
        ),
    ]
