# Generated by Django 5.0 on 2023-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_route_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(choices=[('Oshodi', 'Oshodi'), ('Cele Exp.', 'Cele Exp.'), ('Ajah', 'Ajah'), ('Lekki', 'Lekki'), ('Festac', 'Festac'), ('Ojota', 'Ojota')], max_length=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='pickup',
            field=models.CharField(choices=[('Oshodi', 'Oshodi'), ('Cele Exp.', 'Cele Exp.'), ('Ajah', 'Ajah'), ('Lekki', 'Lekki'), ('Festac', 'Festac'), ('Ojota', 'Ojota')], default='Oshodi', max_length=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_time',
            field=models.CharField(choices=[('07:00', '07:00'), ('08:00', '08:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('17:00', '17:00')], max_length=15),
        ),
        migrations.AlterField(
            model_name='route',
            name='trip',
            field=models.CharField(choices=[('One way', 'One way'), ('Two way', 'Two way')], default='Two way', max_length=20),
        ),
    ]
